system:
    admin_group:
        admin_ui_forms:
            content_edit_form_templates:
                - { template: '@ibexadesign/content/imagemap_form_fields.html.twig', priority: 1 }

    default:
        field_templates:
            - { template: '@ibexadesign/fields/imagemap_content_fields.html.twig', priority: 0 }
